---
- name: copy over sources.list
  copy: src=sources.list
        dest=/etc/apt/sources.list
        owner=root
        group=root
        mode=0644

- name: copy over apt preferences
  copy: src=preferences
        dest=/etc/apt/preferences
        owner=root
        group=root
        mode=0644

- name: make /root/.ssh directory if it does not exist
  file: path=/root/.ssh/
        owner=root
        group=root
        state=directory

- name: install latest ssh pubkeys
  get_url: url=https://github.com/{{ github_user }}.keys
           dest=/root/.ssh/authorized_keys
           owner=root
           group=root
           mode=0644

- name: update apt cache
  raw: apt-get update

- name: install python-apt
  raw: apt-get -y install python-apt

- name: apt-get upgrade
  apt: upgrade=yes

- name: purge nano
  apt: state=abset
       purge=yes
       pkg=nano

- name: apt-get install required files
  apt: state=latest name=$item update_cache=yes
  with_items:
  - build-essential
  - curl
  - dnsutils
  - docker.io
  - git
  - htop
  - mtr-tiny
  - python
  - python-dev
  - python-pip
  - python-setuptools
  - rsync
  - screen
  - sudo
  - vim
  - wget
  - zsh

